server:
  port: 8091

spring:
  #  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
#
  h2:
   console:
     settings:
       web-allow-others: true
     path: /h2
     enabled: true
  datasource:
    url: jdbc:h2:mem:migros
    driverClassName: org.h2.Driver
    username: migros
    password:
  redis:
    host: redis
    port: 6379